### ISSUE TITLE
Style issues with blog articles

### ISSUE THREAD

**Issue by milesw** [thirdandgrove/thirdandgrove-com-gatsby#320]
Love what you all are doing here, and thanks for open-sourcing this repo! 🤩

I noticed a couple minor issues in the blog article announcing this repo and figured this was the best place to report.

**Issues**

1. Links within blog article do not have any styles applied and therefore blend into text.
2. Headings have pound signs preceding them, indicating a markdown issue.

**Details**

- [Screenshot](https://cl.ly/39fa872fb29d)
- [Blog article](https://www.thirdandgrove.com/insights/open-source-gatsby-front-end/)

**Comment by grantglidewell** [comment]
Thanks for this, we fixed the content (hashtag) issue, and are working on the styling issue for links.
